IEV-13
selsa-inube/ievent pull request #10
Opened 2024-07-03 22:34 UTC by Brandonz07

2024-07-04 06:19 UTC, novadeveloper14 requested changes

2024-07-04 06:19 UTC, novadeveloper14 commented on src/pages/queues/outlets/queuesInProgress/config/table.tsx
In the following location of the application *"src\components\data\Table\stories\mocks.tsx"* we have a file where the storybook of the table component is configured

(Storybook is a development tool used to build and document user interface (UI) components. It is not a complete framework, but rather a library that can be integrated into your existing project, whether you are using React, Vue, Angular, Svelte, or other JavaScript frameworks.). To deploy it in our project we must enter the following code in the console:

```
npm run storybook
```

Here if we enter the table component we realize that it is also showing the calendar so we should eliminate it in the same way as was done in the application in the array called actionsResponsiveMock eliminate the id date as follows:

![image](https://github.com/selsa-inube/ievent/assets/87447257/d466b16e-0731-4ffc-b911-0dae56d91e6a)

```
const actionsResponsiveMock = [
  {
    id: "Status",
    actionName: "",
    content: () => <Icon appearance="danger" icon={<MdCancel />} size="20px" />,
  },
  {
    id: "Details",
    actionName: "Detalles",
    content: () => (
      <Icon appearance="dark" icon={<MdOutlineRemoveRedEye />} size="16px" />
    ),
  },
];
```
Don't forget to remove the import of the icon at the beginning of the file.

2024-07-04 14:17 UTC, Brandonz07 commented on src/pages/queues/outlets/queuesInProgress/config/table.tsx
remove the iMovil, and the icon from both `actionsResponsiveConfig` and `infoDataTable`

2024-07-04 14:18 UTC, Brandonz07 commented on src/pages/queues/outlets/queuesInProgress/config/table.tsx
remove icon in stories

2024-07-04 17:02 UTC, novadeveloper14 approved these changes

2024-07-10 10:19 UTC, carin91 requested changes
Your version lacks the borders. Adjust the app to the figma wireframes.
![image](https://github.com/selsa-inube/ievent/assets/123512032/1307be87-832a-4413-b796-c7cad5174842)

2024-07-16 15:27 UTC, merged