Adjust date format
selsa-inube/ievent pull request #11
Opened 2024-07-04 16:03 UTC by Brandonz07

2024-07-04 17:35 UTC, novadeveloper14 requested changes

2024-07-04 17:35 UTC, novadeveloper14 commented on src/components/data/Table/stories/Table.Paginations.stories.tsx
The format is dd/Mmm/yyyy and it is left yyyy/Mmm/dd

2024-07-04 17:35 UTC, novadeveloper14 commented on src/pages/queues/outlets/queuesInProgress/utils.tsx
Let's base it on the following function but modify it so that the time is displayed as required in this project

```
const formatPrimaryDate = (date: Date, withTime?: boolean): string => {
  const months = [
    "Ene",
    "Feb",
    "Mar",
    "Abr",
    "May",
    "Jun",
    "Jul",
    "Ago",
    "Sep",
    "Oct",
    "Nov",
    "Dic",
  ];

  const day = date.getUTCDate().toString().padStart(2, "0");
  const month = months[date.getUTCMonth()];
  const year = date.getUTCFullYear();

  if (withTime) {
    let hours = date.getUTCHours();
    const minutes = date.getUTCMinutes().toString().padStart(2, "0");
    const ampm = hours >= 12 ? "pm" : "am";
    hours = hours % 12;
    hours = hours ? hours : 12;

    return `${day}/${month}/${year} ${hours}:${minutes} ${ampm}`;
  } else {
    return `${day}/${month}/${year}`;
  }
};
```

2024-07-04 17:35 UTC, novadeveloper14 commented on src/components/data/Table/stories/mocks.tsx
The format is dd/Mmm/yyyy and it is left yyyy/Mmm/dd

2024-07-04 18:14 UTC, Brandonz07 commented on src/pages/queues/outlets/queuesInProgress/utils.tsx
use the function and change the time

2024-07-05 06:42 UTC, novadeveloper14 approved these changes

2024-07-10 10:22 UTC, carin91 requested changes
(1) Date is still pending, the "Fecha de ejecución máxima"
![image](https://github.com/selsa-inube/ievent/assets/123512032/8f406543-13b3-4ec1-bcda-65f69dc8f364)

2024-07-10 10:22 UTC, carin91 approved these changes

2024-07-10 14:31 UTC, merged