Implement Logout
selsa-inube/ievent pull request #12
Opened 2024-07-09 13:35 UTC by Brandonz07

2024-07-10 07:24 UTC, novadeveloper14 requested changes

2024-07-10 07:24 UTC, novadeveloper14 commented on src/components/navigation/MenuItem/index.tsx
the text is not centered:

IEvent
![image](https://github.com/selsa-inube/ievent/assets/87447257/4baf1aa9-4144-4a09-955e-f50ebbcc4867)
Crediboard
![image](https://github.com/selsa-inube/ievent/assets/87447257/c5211b62-a1af-48da-85ea-7132a3ba8c2f)

The separation line is becoming very dark, that is not the color it should be.

there is more space to the left than to the right of the component

2024-07-10 07:24 UTC, novadeveloper14 commented on src/components/feedback/LogoutModal/index.tsx
> +                <Icon
It should have a cursor when hovering in the component with cursorHover prop

2024-07-10 17:23 UTC, Brandonz07 commented on src/components/feedback/LogoutModal/LogoutModal.stories.tsx
> +import { BrowserRouter } from "react-router-dom";
i fix imports

2024-07-10 17:24 UTC, Brandonz07 commented on src/components/navigation/MenuItem/index.tsx
center text, change color and center divider

2024-07-10 17:24 UTC, Brandonz07 commented on src/components/feedback/LogoutModal/index.tsx
> +                <Icon
add hover

2024-07-11 12:50 UTC, novadeveloper14 commented on src/components/navigation/MenuUser/styles.ts
> +const StyledAvatarContainer = styled.div`
Instead of creating the styled components, you could set the margin and sizes to the parent Stack of the component:

https://github.com/selsa-inube/design-system/blob/main/src/components/layouts/Stack/index.tsx

2024-07-11 12:50 UTC, novadeveloper14 commented on src/components/navigation/MenuItem/styles.ts
> +  & > div > div{
This must be done in the index through the component props

2024-07-11 12:52 UTC, novadeveloper14 commented on src/components/navigation/MenuSection/index.tsx
>  import { Divider } from "@src/components/layout/Divider";
You could directly use the import of the folders, verify that this does not happen in other files

import { Divider } from "@components/layout/Divider";

2024-07-11 15:07 UTC, Brandonz07 commented on src/components/navigation/MenuUser/styles.ts
> +const StyledAvatarContainer = styled.div`
i remove styled

2024-07-11 21:21 UTC, novadeveloper14 approved these changes

2024-07-17 09:54 UTC, carin91 approved these changes

2024-07-17 09:54 UTC, merged