iev17 Change business unit
selsa-inube/ievent pull request #18
Opened 2024-08-16 19:19 UTC by Brandonz07

2024-08-22 16:46 UTC, novadeveloper14 approved these changes

2024-08-26 11:33 UTC, carin91 requested changes

2024-08-26 11:33 UTC, carin91 commented on src/components/inputs/BusinessUnitChange/index.tsx
> +                  size="20px"
Hold consistency between icons sizes.
![image](https://github.com/user-attachments/assets/4b59dd58-0227-42f0-9c33-9f445fa0ce0f)
Verify the correct size, however i found a 24px for MdInfoOutline icon

2024-08-26 11:33 UTC, carin91 commented on src/components/inputs/BusinessUnitChange/index.tsx
> +                <Icon
The check icon should be rendered before the first click based on the selected business unit.
![image](https://github.com/user-attachments/assets/d9e2d59e-0dcd-442b-8167-acded662d2c7)

2024-08-26 11:33 UTC, carin91 commented on src/components/layout/AppPage/index.tsx
> +            <Icon
Hold consistency between icons sizes.
![image](https://github.com/user-attachments/assets/4b59dd58-0227-42f0-9c33-9f445fa0ce0f)
Verify the correct size, however i found a 24px for MdInfoOutline icon

2024-08-26 11:33 UTC, carin91 commented on src/components/layout/AppPage/index.tsx
> +            <Icon
The icon position seems invalid, it is not centered with the business unit logo
![image](https://github.com/user-attachments/assets/d9e2d59e-0dcd-442b-8167-acded662d2c7)

2024-08-26 11:33 UTC, carin91 commented on src/components/layout/AppPage/index.tsx
> +        <StyledCollapseIcon $collapse={collapse} onClick={() =>  setCollapse(!collapse)} $isTablet={isTablet}>
(1) The dropdown of the business unit should close when the user clicks outside of it.

2024-08-26 11:33 UTC, carin91 commented on src/components/inputs/BusinessUnitChange/index.tsx
> +    <StyledContainer>
Adjust the responsive behavior, the position of the dropdown seems invalid considering the view of the searcher, add to it, the logos and icons seem bigger than the selected logo/icon 
![image](https://github.com/user-attachments/assets/f4c98a54-edf6-476d-967e-387e1ad3ff3e)

2024-09-06 02:00 UTC, carin91 approved these changes

2024-09-06 02:00 UTC, merged