create modal view in consultation table
selsa-inube/ievent pull request #7
Opened 2024-06-07 23:55 UTC by ANGIECATHERINEP

Create modal view in consultation table in queues-in-progress

2024-06-13 05:41 UTC, novadeveloper14 approved these changes
El desarrollo es correcto

2024-06-13 09:41 UTC, carin91 requested changes

2024-06-13 09:41 UTC, carin91 commented on .storybook/main.ts
> +  async viteFinal(config) {
why do we need this change?

2024-06-13 09:41 UTC, carin91 commented on src/components/feedback/InteractiveModal/index.tsx
> +  actions?: IAction[];
This prop is not in use, can you delete it?

2024-06-13 09:41 UTC, carin91 commented on src/components/feedback/InteractiveModal/styles.ts
> +  background-color: ${inube.palette.neutral.N10};
Define a theme validation, for future implementation of a theme provider.

2024-06-13 09:41 UTC, carin91 commented on src/pages/queues/outlets/queuesInProgress/components/DetailsModal/index.tsx
> +interface IDetailsModalProps {
is it necessary? the DetailsModal has just 1 prop, however, you have an interface + destructuring. It is good to hold a standard to improve consistency, however, it is important to write code as simply as possible. Reevaluate this solution.

2024-06-13 17:12 UTC, ANGIECATHERINEP commented on .storybook/main.ts
> +  async viteFinal(config) {
resolved

2024-06-13 17:12 UTC, ANGIECATHERINEP commented on src/components/feedback/InteractiveModal/index.tsx
> +  actions?: IAction[];
resolved

2024-06-13 17:13 UTC, ANGIECATHERINEP commented on src/components/feedback/InteractiveModal/styles.ts
> +  background-color: ${inube.palette.neutral.N10};
resolved

2024-06-13 17:13 UTC, ANGIECATHERINEP commented on src/pages/queues/outlets/queuesInProgress/components/DetailsModal/index.tsx
> +interface IDetailsModalProps {
resolved

2024-06-14 09:35 UTC, carin91 approved these changes

2024-06-14 09:35 UTC, merged